# FONT.
TITLE_FONT = "Rockwell"
VALUE_FONT = "JetBrains Mono"

# COLORS.
WHITE = "#FFF"
GREY = "GREY"
BLUE = "#1F6AA5"
DARK_GREY = "#4A4A4A"
CLOSE_RED = "#8A0606"
SLIDER_BG = "#64686B"
CANVAS_BG = "#242424"
DROPDOWN_MAIN = "#444"
DROPDOWN_HOVER = "#333"
DROPDOWN_MENU = "#666"

# AFFINE.
DEFAULT_ROTATE = DEFAULT_ZOOM = 0
FLIP_OPTIONS = ("NONE", "X", "Y", "BOTH")
# COLOUR.
DEFAULT_GRAYSCALE = DEFAULT_INVERT = False
DEFAULT_EQUALIZE = DEFAULT_POSTERIZE = 0
DEFAULT_SOLARIZE = 255
DEFAULT_BRIGHTNESS = DEFAULT_VIBRANCE = DEFAULT_CONTRAST = DEFAULT_SHARPNESS = 1
# EFFECTS.
EFFECT_OPTIONS = ("NONE", "BLUR", "CONTOUR", "DETAIL", "EDGE ENHANCE", "EMBOSS", "FIND EDGES", "SHARPEN", "SMOOTH")
FILTER_OPTIONS = ("NONE", "MEDIAN FILTER", "LOWPASS FILTER", "HIGHPASS FILTER", "FREQUENCY FILTER")
DEFAULT_BOXBLUR = DEFAULT_GAUSSIANBLUR = DEFAULT_UNSHARPMASK = 0
